page:
  side: left
  margin_width: 330
  margin_color: '#000'

layer_defs:
    tentantLayer:
        shape: platformLayer
        gradient_front: '#0011d0'
        gradient_back: '#222'
    firmLayer:
        shape: stackLayer
        gradient_front: '#0055d4'
        gradient_back: '#000'
    rhLayer:
        shape: stackLayer
        gradient_front: '#f91100'
        gradient_back: '#000'
    metalLayer:
        shape: stackLayer
        gradient_front: '#777'
        gradient_back: '#000'
        
# for every 30 title chars move the text up __ pixels

ribbon_layer: workloadLayer

layers:
    - id: workloadLayer
      labels: 
      - TENANT WORKLOADS
      style: title
      layer_def: tentantLayer
    - id: selfServiceApi
      labels: 
      - SELF-SERVICE EXPERIENCE 
      - '&amp; API'
      layer_def: firmLayer
    - id: controlLayer
      labels: 
      - RISK, COMPLIANCE, 
      - BILLING, OBSERVABILITY
      layer_def: firmLayer
    - id: identityLayer
      labels: 
      - INVENTORY, IDENTITY, POLICY, 
      - FIRM CLOUD API
      layer_def: firmLayer
    - id: vpcLayer
      labels: 
      - VPC, SEGMENTATION, 
      - POLICY ENFORCEMENT  
      layer_def: rhLayer
    - id: sdsLayer
      labels: 
      - BLOCK, FILE, OBJECT 
      - STORAGE AS A SERVICE
      layer_def: rhLayer
    - id: sdnLayer
      labels: 
      - SOFTWARE DEFINED NETWORK
      layer_def: rhLayer
    - id: sdnLayer
      labels: 
      - KUBERNETES BASED VIRTUALIZATION 
      - '&amp; CONTAINERS'
      layer_def: rhLayer
    - id: acceleratorsLayer
      labels: 
      - ACCELERATORS
      layer_def: metalLayer
    - id: metalLayer
      labels: 
      - NEXT-GEN PHYSICAL
      - COMPUTE, 
      - NETWORK, STORAGE
      layer_def: metalLayer
      
      