page:
  side: left
  margin_width: 330
  margin_color: '#000'

layer_defs:
    tentantLayer:
        shape: platformLayer
        gradient_front: '#0011d0'
        gradient_back: '#222'
    firmLayer:
        shape: stackLayer
        gradient_front: '#0055d4'
        gradient_back: '#000'
    rhLayer:
        shape: stackLayer
        gradient_front: '#f91100'
        gradient_back: '#000'
    metalLayer:
        shape: stackLayer
        gradient_front: '#777'
        gradient_back: '#000'
        
# for every 30 title chars move the text up __ pixels

layers:
    - id: workloadLayer
      label: TENANT WORKLOADS
      style: title
      layer_def: tentantLayer
    - id: selfServiceApi
      label: SELF-SERVICE EXPERIENCE &amp; API
      layer_def: firmLayer
    - id: controlLayer
      label: RISK, COMPLIANCE, BILLING, OBSERVABILITY
      layer_def: firmLayer
    - id: identityLayer
      label: IDENTITY, INVENTORY, POLICY, FIRM CLOUD API
      layer_def: firmLayer
    - id: vpcLayer
      label: VIRTUAL PRIVATE CLOUDS, SEGMENTATION, POLICY CONTROL  
      layer_def: rhLayer
    - id: sdsLayer
      label: BLOCK, FILE, OBJECT STORAGE AS A SERVICE
      layer_def: rhLayer
    - id: sdnLayer
      label: SOFTWARE DEFINED NETWORK
      layer_def: rhLayer
    - id: sdnLayer
      label: KUBERNETES BASED VIRTUALIZATION &amp; CONTAINERS
      layer_def: rhLayer
    - id: acceleratorsLayer
      label: ACCELERATORS
      layer_def: metalLayer
    - id: metalLayer
      label: NEXT-GEN PHYSICAL NETWORK, COMPUTE, STORAGE
      layer_def: metalLayer
      
      