page:
  side: left
  margin_width: 330
  margin_color: '#000'

layer_defs:
    tentantLayer:
        shape: platformLayer
        gradient_front: '#0011d0'
        gradient_back: '#222'
    firmLayer:
        shape: stackLayer
        gradient_front: '#0055d4'
        gradient_back: '#000'
    rhLayer:
        shape: stackLayer
        gradient_front: '#f91100'
        gradient_back: '#000'
    metalLayer:
        shape: stackLayer
        gradient_front: '#777'
        gradient_back: '#000'

ribbon_layer: policyLayer

layers:
    - id: workloadLayer
      labels: 
      - TENANT WORKLOADS
      style: title
      layer_def: tentantLayer
    - id: selfServiceApi
      labels: 
      - SELF-SERVICE EXPERIENCE 
      - '&amp; API'
      layer_def: firmLayer
    - id: controlLayer
      labels: 
      - RISK, COMPLIANCE, 
      - BILLING, OBSERVABILITY
      layer_def: firmLayer
    - id: identityLayer
      labels: 
      - INVENTORY, IDENTITY, POLICY, 
      - FIRM CLOUD API
      layer_def: firmLayer
    - id: vpcLayer
      labels: 
      - VPC, 
      - SEGMENTATION 
      layer_def: rhLayer
    - id: policyLayer
      labels: 
      - POLICY ENFORCEMENT 
      layer_def: rhLayer
    - id: sdsLayer
      labels: 
      - BLOCK, FILE, OBJECT 
      - STORAGE AS A SERVICE
      layer_def: rhLayer
    - id: sdnLayer
      labels: 
      - SOFTWARE DEFINED 
      - NETWORK
      layer_def: rhLayer
    - id: sdnLayer
      labels: 
      - KUBERNETES BASED
      - 'VIRT &amp; CONTAINERS'
      layer_def: rhLayer
    - id: osLayer
      labels: 
      - RED HAT
      - COREOS LINUX
      layer_def: rhLayer
    - id: acceleratorsLayer
      labels: 
      - ACCELERATORS
      layer_def: metalLayer
    - id: metalLayer
      labels: 
      - NEXT-GEN PHYSICAL
      - COMPUTE, 
      - NETWORK, STORAGE
      layer_def: metalLayer
      
content: 
    - id: PCP073 
      level1: Principles
      level2: Governance
      level3: Encapsulation
      title: Provide abstraction at higher levels of the stack to provide long-term supported models, and further control at course gained consumption at lower levels.
      body: 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor 
        incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis 
        nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore 
        eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt 
        in culpa qui officia deserunt mollit anim id est laborum.
        
        
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor 
        incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis 
        nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore 
        eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt 
        in culpa qui officia deserunt mollit anim id est laborum.
        
        
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor 
        incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis 
        nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore 
        eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt 
        in culpa qui officia deserunt mollit anim id est laborum.
        
        
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor 
        incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis 
        nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore 
        eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt 
        in culpa qui officia deserunt mollit anim id est laborum.
        
        
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor 
        incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis 
        nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore 
        eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt 
        in culpa qui officia deserunt mollit anim id est laborum.
        
        
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor 
        incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis 
        nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

      
      